env:
  - distro: debianjessie
    init: "/sbin/init"

services:
  - docker

script:
  - container_id=$(mktemp)
  - docker build -t container_under_test .
  - docker run --detach container_under_test -p 3030:3030 -p 4567:4567 "${init}" > "${container_id}"
  - curl 'http://localhost:4567/info'
